export interface Product {
  name: string
  slug: string
  tagline: string
  brandName: string
  genericName: string
  icon: string
  iconColor: string
  images: { src: string; alt: string }[]
  composition: string
  description: string
  shortDescription: string
  benefits: string[]
  indications: string[]
  dosage: string
  storage: string
  packaging?: string
  manufacturer?: string
  category: string
}

export const productsData: Record<string, Product> = {
  "mi-sum-vit": {
    name: "Mi Sum Vit™ Tablets",
    slug: "mi-sum-vit",
    brandName: "Mi Sum Vit",
    genericName: "Multivitamin & Antioxidant Complex",
    tagline: "Complete Multivitamin & Antioxidant Supplement",
    icon: "Pill",
    iconColor: "#28A745",
    category: "Multivitamins",
    images: [
      { src: "/products/mi-cal-zm-1.jpg", alt: "Mi Sum Vit Tablets - Front View" },
      { src: "/products/mi-cal-zm-2.jpg", alt: "Mi Sum Vit Tablets - Side View with Details" },
      { src: "/products/mi-cal-zm-3.jpg", alt: "Mi Sum Vit Tablets - With Blister Pack" },
    ],
    composition: "Lycopene, Cyanocobalamin, Multimineral, Multivitamin & Antioxidants",
    shortDescription: "Complete multivitamin and antioxidant supplement for optimal health and well-being.",
    description: "Mi Sum Vit™ is a comprehensive multivitamin and antioxidant supplement designed to support overall health and well-being. This powerful formula combines essential vitamins, minerals, and antioxidants to help fill nutritional gaps and promote optimal body function.",
    benefits: [
      "Supports overall health and well-being",
      "Provides essential vitamins and minerals",
      "Antioxidant protection against free radicals",
      "Boosts immune system function",
      "Supports energy metabolism",
      "Promotes healthy skin, hair, and nails",
    ],
    indications: [
      "Vitamin and mineral deficiency",
      "Weak immune system",
      "General fatigue and weakness",
      "Poor dietary intake",
      "Stressful lifestyle",
    ],
    dosage: "One tablet daily after meals or as directed by the physician.",
    storage: "Store in a cool, dry place away from direct sunlight. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "mi-red-z-one": {
    name: "Mi Red Z One™ Tablets",
    slug: "mi-red-z-one",
    brandName: "Mi Red Z One",
    genericName: "Ferrous Ascorbate, Folic Acid & Zinc",
    tagline: "Iron, Folic Acid & Zinc Supplement",
    icon: "Heart",
    iconColor: "#FF0000",
    category: "Hematinic Supplements",
    images: [
      { src: "/products/mi-red-z-one-1.jpg", alt: "Mi Red Z One Tablets - Front View" },
      { src: "/products/mi-red-z-one-2.jpg", alt: "Mi Red Z One Tablets - With Blister Pack" },
    ],
    composition: "Ferrous Ascorbate, Folic Acid & Zinc Sulphate",
    shortDescription: "Iron supplement with folic acid and zinc for optimal blood health and vitality.",
    description: "Mi Red Z One™ is a specialized iron supplement formulated to support optimal blood health. Combining ferrous ascorbate with folic acid and zinc, this product helps combat iron deficiency and supports overall vitality.",
    benefits: [
      "Helps combat iron deficiency anemia",
      "Supports healthy red blood cell formation",
      "Improves iron absorption",
      "Enhances energy levels",
      "Supports cognitive function",
      "Promotes overall vitality",
    ],
    indications: [
      "Iron deficiency anemia",
      "Pregnancy and lactation",
      "Menstrual disorders",
      "Poor iron absorption",
      "General weakness and fatigue",
    ],
    dosage: "One tablet daily or as directed by the physician.",
    storage: "Store in a cool, dry place away from direct sunlight. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "mi-cal-zm": {
    name: "Mi Cal ZM™ Tablets",
    slug: "mi-cal-zm",
    brandName: "Mi Cal ZM",
    genericName: "Calcium, Vitamin D3, Magnesium & Zinc",
    tagline: "Calcium, Vitamin D3, Magnesium & Zinc",
    icon: "Bone",
    iconColor: "#FF6200",
    category: "Bone Health",
    images: [
      { src: "/products/mi-sum-vit-1.jpg", alt: "Mi Cal ZM Tablets - Front View" },
      { src: "/products/mi-sum-vit-2.jpg", alt: "Mi Cal ZM Tablets - Side View with Details" },
      { src: "/products/mi-sum-vit-3.jpg", alt: "Mi Cal ZM Tablets - With Blister Pack" },
    ],
    composition: "Calcium Citrate Malate, Vitamin D3, Magnesium & Zinc Sulphate",
    shortDescription: "Comprehensive bone health supplement with calcium, vitamin D3, magnesium, and zinc for strong bones.",
    description: "Mi Cal ZM™ is a comprehensive bone health supplement specially formulated for pregnant and lactating women. This advanced formula provides essential calcium, vitamin D3, magnesium, and zinc to support strong bones and overall health.",
    benefits: [
      "Supports bone health and strength",
      "Ideal for pregnant and lactating women",
      "Enhances calcium absorption",
      "Supports muscle function",
      "Maintains bone mineral density",
      "Promotes overall skeletal health",
    ],
    indications: [
      "Calcium deficiency",
      "Pregnancy and lactation",
      "Osteoporosis prevention",
      "Bone weakness",
      "Postmenopausal women",
    ],
    dosage: "One tablet twice daily or as directed by the physician.",
    storage: "Store in a cool, dry place away from direct sunlight.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "mi-cal-k2": {
    name: "Mi Cal K2™ Tablets",
    slug: "mi-cal-k2",
    brandName: "Mi Cal K2",
    genericName: "Calcium Citrate, Menatetrenone & Vitamin D3",
    tagline: "Complete Bone Health & Calcium Supplement",
    icon: "Bone",
    iconColor: "#9333EA",
    category: "Bone Health",
    images: [
      { src: "/products/mi1.jpg", alt: "Mi Cal K2 Tablets - Front View" },
      { src: "/products/mi2.jpg", alt: "Mi Cal K2 Tablets - Side View" },
    ],
    composition: "Calcium Citrate, Menatetrenone (Vitamin K2), Cholecalciferol (Vitamin D3) & Magnesium",
    shortDescription: "Complete bone health supplement combining calcium, vitamin K2, and vitamin D3 for stronger bones.",
    description: "Mi Cal K2™ is an advanced bone health supplement combining calcium citrate with vitamin K2 and vitamin D3. This scientifically formulated product supports bone density, strength, and overall skeletal health, making it ideal for children, women, and older adults.",
    benefits: [
      "Supports bone density and strength",
      "Enhances calcium absorption and utilization",
      "Vitamin K2 directs calcium to bones",
      "Vitamin D3 supports calcium metabolism",
      "Reduces risk of osteoporosis",
      "Supports overall skeletal health",
    ],
    indications: [
      "Calcium deficiency",
      "Low bone density",
      "Osteoporosis prevention",
      "Post-menopausal women",
      "Children growth and development",
      "Older adults bone health",
    ],
    dosage: "One tablet daily with meals or as directed by the physician.",
    storage: "Store in a cool, dry place away from direct sunlight. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "mi-l-gest": {
    name: "Mi L Gest™ Tablets",
    slug: "mi-l-gest",
    brandName: "Mi L Gest",
    genericName: "Progesterone",
    tagline: "Pregnancy Support & Luteal Phase Supplement",
    icon: "Heart",
    iconColor: "#E91E63",
    category: "Women Health",
    images: [
      { src: "/products/mi-l-gest-1.jpg", alt: "Mi L Gest Tablets - Front View" },
      { src: "/products/mi-l-gest-2.jpg", alt: "Mi L Gest Tablets - With Blister Pack" },
    ],
    composition: "Micronized Progesterone 200 mg",
    shortDescription: "Natural progesterone supplement for pregnancy support and women's reproductive health.",
    description: "Mi L Gest™ provides micronized progesterone to support pregnancy maintenance and women's reproductive health. This naturally derived hormone helps maintain healthy luteal phase function and supports overall hormonal balance during pregnancy.",
    benefits: [
      "Supports pregnancy maintenance",
      "Promotes healthy luteal phase",
      "Helps prevent recurrent miscarriage",
      "Supports hormonal balance",
      "Aids in conception support",
      "Natural hormone replacement option",
    ],
    indications: [
      "Luteal phase support",
      "Recurrent pregnancy loss",
      "Progesterone deficiency",
      "Pregnancy maintenance (first trimester)",
      "Assisted reproductive therapy support",
      "Hormonal imbalance",
    ],
    dosage: "As directed by the physician. Typically 200 mg once or twice daily.",
    storage: "Store in a cool, dry place below 25°C. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "mi-d-max": {
    name: "Mi D Max™ Tablets",
    slug: "mi-d-max",
    brandName: "Mi D Max",
    genericName: "Vitamin D3 & Calcium",
    tagline: "Vitamin D3 & Calcium Supplement for Bone Health",
    icon: "Sun",
    iconColor: "#FFC107",
    category: "Micronutrients",
    images: [
      { src: "/products/mi-d-max-1.jpg", alt: "Mi D Max Tablets - Front View" },
      { src: "/products/mi-d-max-2.jpg", alt: "Mi D Max Tablets - Side View" },
    ],
    composition: "Cholecalciferol (Vitamin D3) 1000 IU & Calcium Citrate 250 mg",
    shortDescription: "Vitamin D3 and calcium supplement for optimal bone health and calcium absorption.",
    description: "Mi D Max™ combines high-potency vitamin D3 with absorbable calcium citrate to support optimal bone health and calcium metabolism. This powerful combination helps maintain strong bones and supports overall skeletal function.",
    benefits: [
      "Supports calcium absorption and utilization",
      "Maintains optimal bone density",
      "Supports immune system function",
      "Promotes musculoskeletal health",
      "Enhances overall wellness",
      "Supports physical activity tolerance",
    ],
    indications: [
      "Vitamin D deficiency",
      "Low calcium intake",
      "Bone health support",
      "Seasonal mood changes",
      "Immune system support",
      "General wellness",
    ],
    dosage: "One tablet daily with food or as directed by the physician.",
    storage: "Store in a cool, dry place away from direct sunlight. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "ferti-fa-q10": {
    name: "Ferti Fa - Q10™ Tablets",
    slug: "ferti-fa-q10",
    brandName: "Ferti Fa - Q10",
    genericName: "CoQ10, Lycopene & Fertility Complex",
    tagline: "Premium Fertility & Reproductive Health Support",
    icon: "Dna",
    iconColor: "#28A745",
    category: "Fertility",
    images: [
      { src: "/products/fer1.jpg", alt: "Ferti Fa - Q10 Tablets - Front View" },
    ],
    composition: "Ubiquinol, Lycopene, L-Carnitine, L-Arginine, Folic Acid, Selenium & Astaxanthin",
    shortDescription: "Premium fertility supplement combining CoQ10 and antioxidants for enhanced reproductive health.",
    description: "Ferti Fa - Q10™ is a premium fertility supplement designed to support reproductive health for both men and women. This advanced formula combines powerful antioxidants and essential nutrients to enhance fertility and support overall reproductive function.",
    benefits: [
      "Supports male and female fertility",
      "Powerful antioxidant protection",
      "Enhances sperm health",
      "Supports ovarian function",
      "Promotes hormonal balance",
      "Improves reproductive health",
    ],
    indications: [
      "Couples trying to conceive",
      "Male infertility",
      "Female infertility",
      "PCOS support",
      "Low ovarian reserve",
      "Age-related fertility concerns",
    ],
    dosage: "One tablet daily or as directed by the physician.",
    storage: "Store in a cool, dry place away from direct sunlight.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "doxy-mil-od": {
    name: "Doxy Mil-OD™ Tablets",
    slug: "doxy-mil-od",
    brandName: "Doxy Mil-OD",
    genericName: "Doxylamine Succinate & Pyridoxine",
    tagline: "Pregnancy Nausea & Vomiting Relief",
    icon: "Heart",
    iconColor: "#E91E63",
    category: "Maternal Care",
    images: [
      { src: "/products/Doxy Mil-OD.jpeg", alt: "Doxy Mil-OD Tablets - Front View" },
      { src: "/products/Doxy Mil-od (2).jpeg", alt: "Doxy Mil-OD Tablets - Side View" },
    ],
    composition: "Doxylamine Succinate, Pyridoxine Hydrochloride (Vitamin B6)",
    shortDescription: "Safe and effective relief from pregnancy nausea and vomiting.",
    description: "Doxy Mil-OD™ is a specially formulated supplement combining an antihistamine and Vitamin B6 to provide safe and effective relief from nausea and vomiting during pregnancy. This maternal care formula supports expectant mothers with synergistic relief and improved comfort throughout pregnancy.",
    benefits: [
      "Effectively reduces nausea and vomiting during pregnancy",
      "Combines antihistamine + Vitamin B6 for synergistic relief",
      "Helps improve appetite and hydration in expectant mothers",
      "Safe and well-tolerated when used as prescribed",
      "Supports maternal comfort and daily functioning",
    ],
    indications: [
      "Nausea and vomiting of pregnancy (NVP)",
      "Morning sickness in early pregnancy",
      "Persistent pregnancy-related nausea unresponsive to diet changes",
      "Prevention of recurrent nausea episodes in pregnancy",
      "Supportive therapy for mild to moderate hyperemesis gravidarum",
    ],
    dosage: "As directed by the physician. Typically 1 tablet daily (preferably at bedtime) or as prescribed based on symptom severity.",
    storage: "Store in a cool, dry place below 25°C. Protect from light and moisture. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "etomil-90": {
    name: "Etomil-90™ Tablets",
    slug: "etomil-90",
    brandName: "Etomil-90",
    genericName: "Etoricoxib 90mg",
    tagline: "Advanced COX-2 Inhibitor Pain Relief",
    icon: "Bone",
    iconColor: "#9333EA",
    category: "Pain Management",
    images: [
      { src: "/products/ETOMIL-90.jpeg", alt: "Etomil-90 Tablets - Front View" },
    ],
    composition: "Etoricoxib 90 mg",
    shortDescription: "Potent selective COX-2 inhibitor for effective pain and inflammation management.",
    description: "Etomil-90™ is a potent selective COX-2 inhibitor designed for long-term management of arthritis and musculoskeletal pain conditions. With once-daily dosing and lower gastric irritation risk, this advanced NSAID provides effective relief while supporting joint mobility and physical function.",
    benefits: [
      "Potent and selective COX-2 inhibition for pain relief",
      "Reduces inflammation and joint swelling",
      "Provides long-lasting analgesic effect with once-daily dosing",
      "Improves joint mobility and physical function",
      "Lower gastric irritation risk compared to non-selective NSAIDs",
    ],
    indications: [
      "Osteoarthritis",
      "Rheumatoid arthritis",
      "Ankylosing spondylitis",
      "Acute musculoskeletal pain",
      "Acute gouty arthritis",
    ],
    dosage: "As directed by the physician. Commonly 90 mg once daily after food or as prescribed based on condition severity.",
    storage: "Store in a cool, dry place below 25°C. Protect from light and moisture. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
  "etomil-mr": {
    name: "EtoMil MR™ Tablets",
    slug: "etomil-mr",
    brandName: "Eto Mil MR",
    genericName: "Etoricoxib & Thiocolchicoside",
    tagline: "Pain Relief & Muscle Relaxation",
    icon: "Activity",
    iconColor: "#007BFF",
    category: "Pain Management",
    images: [
      { src: "/products/eto1.jpg", alt: "EtoMil MR Tablets - Front View" },
      { src: "/products/eto2.jpg", alt: "EtoMil MR Tablets - With Blister Pack" },
    ],
    composition: "Etoricoxib 60mg and Thiocolchicoside 4mg",
    shortDescription: "Dual-action formula combining pain relief with muscle relaxation for maximum therapeutic benefit.",
    description: "Eto Mil MR™ is a powerful combination medication designed for effective pain management and muscle relaxation. This dual-action formula combines potent anti-inflammatory effects with muscle relaxant properties, making it ideal for acute and chronic musculoskeletal conditions.",
    benefits: [
      "Dual action: anti-inflammatory + muscle relaxant",
      "Provides effective relief from acute musculoskeletal pain",
      "Reduces inflammation, swelling, and stiffness",
      "Relieves muscle spasm and improves mobility",
      "Faster functional recovery in painful conditions",
    ],
    indications: [
      "Acute low back pain",
      "Cervical and lumbar spondylosis",
      "Muscular spasm and strain",
      "Osteoarthritis with muscle spasm",
      "Post-traumatic or post-operative musculoskeletal pain",
    ],
    dosage: "As directed by the physician. Typically 1 tablet once daily after food or as prescribed.",
    storage: "Store in a cool, dry place below 25°C. Protect from light and moisture. Keep out of reach of children.",
    packaging: "10 X 10 ALU-ALU Blister",
    manufacturer: "Milun Pharmaceuticals Limited",
  },
}

export function getProductBySlug(slug: string): Product | undefined {
  return productsData[slug]
}

export function getAllProducts(): Product[] {
  return Object.values(productsData)
}

export function getAllProductSlugs(): string[] {
  return Object.keys(productsData)
}
